FROM golang:1.18-alpine

RUN mkdir /app

RUN addgroup -S bilgroup
RUN adduser -S -D -h /app biluser bilgroup
RUN chown -R biluser:bilgroup /app
USER biluser

COPY main.go /app

EXPOSE 8080
CMD go run /app/main.go